### ISSUE TITLE
GeoHash algorithm not producing expected results

### ISSUE THREAD

**Issue by abrin** [davidmoten/geo#16]
Hi,
  I've been having some issues with generating Geo Hashes of points and then of bounding boxes that I would expect to share a prefix. E.g. this fairly arbitrary point in New Mexico ( 35.37322998046875, -108.7591552734375) should be contained in a rough bounding box of the United States (13.923403897723347, -126.91406249999999  x 55.37911044801047, -74.1796875 ). Am I doing something wrong?

thanks

Unit test below:

```java
package org.digitalantiquity.skope;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.apache.log4j.Logger;
import org.digitalantiquity.skope.service.LuceneIndexingService;
import org.junit.Test;

import com.github.davidmoten.geo.Coverage;
import com.github.davidmoten.geo.GeoHash;
import com.github.davidmoten.geo.LatLong;

public class ShapefileParserTest {

    private final Logger logger = Logger.getLogger(getClass());


    @Test
    public void testHash() {
        double x1 = -126.91406249999999;
        double y1 = 13.923403897723347;
        double x2 = -74.1796875;
        double y2 = 55.37911044801047;
        
        logger.debug(String.format("start (%s,%s) x(%s,%s)", x1, y1, x2, y2));
        String point = "9w69jps00000";
        LatLong latLong = GeoHash.decodeHash(point);
        logger.debug(latLong);
        String hash2 = GeoHash.encodeHash(35.37322998046875, -108.7591552734375);
        assertEquals(hash2, point);
        logger.debug(hash2);
        Coverage coverage = GeoHash.coverBoundingBox(x1,y1,x2,y2,4);
        boolean seen = false;
        logger.debug(coverage);
        for (String hash : coverage.getHashes()) {
            if (hash.equals(point) || point.startsWith(hash)) {
                logger.debug(hash + " -> " + GeoHash.decodeHash(hash));
                seen = true;
            }
        }
        assertTrue("should have seen hash",seen);
    }
}
```

**Comment by davidmoten** [comment]
Hi, the issue is that you are providing the parameters in the wrong order
to GeoHash.coverBoundingBox.  the parameters should be topLeftLat,
topLeftLon, bottomRightLat, bottomRightLon.

**Comment by davidmoten** [comment]
By the way, your issue does indicate that some precondition checking is not
taking place because a latitude of -126 should really provoke an
IllegalArgumentException. I'll fix that.
On 8 Mar 2015 17:56, wrote:

Hi, the issue is that you are providing the parameters in the wrong order
to GeoHash.coverBoundingBox.  the parameters should be topLeftLat,
topLeftLon, bottomRightLat, bottomRightLon.
On 8 Mar 2015 07:36, "abrin" <notifications@github.com> wrote:

Hi,
I've been having some issues with generating Geo Hashes of points and then
of bounding boxes that I would expect to share a prefix. E.g. this fairly
arbitrary point in New Mexico ( 35.37322998046875, -108.7591552734375)
should be contained in a rough bounding box of the United States
(13.923403897723347, -126.91406249999999 x 55.37911044801047, -74.1796875
). Am I doing something wrong?

thanks

Unit test below:

package org.digitalantiquity.skope;
import static org.junit.Assert.assertEquals;import static
org.junit.Assert.assertTrue;
import org.apache.log4j.Logger;import
org.digitalantiquity.skope.service.LuceneIndexingService;import
org.junit.Test;
import com.github.davidmoten.geo.Coverage;import
com.github.davidmoten.geo.GeoHash;import
com.github.davidmoten.geo.LatLong;
public class ShapefileParserTest {

    private final Logger logger = Logger.getLogger(getClass());


    @Test
    public void testHash() {
        double x1 = -126.91406249999999;
        double y1 = 13.923403897723347;
        double x2 = -74.1796875;
        double y2 = 55.37911044801047;

        logger.debug(String.format("start (%s,%s) x(%s,%s)", x1, y1, x2, y2));
        String point = "9w69jps00000";
        LatLong latLong = GeoHash.decodeHash(point);
        logger.debug(latLong);
        String hash2 = GeoHash.encodeHash(35.37322998046875,
-108.7591552734375);
        assertEquals(hash2, point);
        logger.debug(hash2);
        Coverage coverage = GeoHash.coverBoundingBox(x1,y1,x2,y2,4);
        boolean seen = false;
        logger.debug(coverage);
        for (String hash : coverage.getHashes()) {
            if (hash.equals(point) || point.startsWith(hash)) {
                logger.debug(hash + " -> " + GeoHash.decodeHash(hash));
                seen = true;
            }
        }
        assertTrue("should have seen hash",seen);
    }
}

—
Reply to this email directly or view it on GitHub
<https://github.com/davidmoten/geo/issues/16>.

**Comment by abrin** [comment]
well that’s stupid (of me). Glad it had the added benefit of finding a validation error.  Thanks for pointing it out.

**Comment by abrin** [comment]
David,
  As I use it a bit, it might be nice to expose both "length" and “max” to the encode functions. Right now, one has to make the choice between either having a number of hashes or a max length of a hash. But, if you’re selecting a larger region it likely becomes important to have access to both.

thanks,

adam
